version: '3.8'

services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:latest
    ports:
      - "5436:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB